[project]
name = "server"
version = "0.1.0"
description = "Drag and Drop Kanban Board server"
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "fastapi[standard]>=0.115.6",
    "websocket>=0.2.1",
]
