version: "3.7"

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    image: kanban-board-server
    container_name: kanban-board-server
    command: /app/.venv/bin/fastapi run app/main.py --port 5000 --host 0.0.0.0 --reload
    volumes:
      - ./server/:/app
      - /app/.venv # anonymous volume for .venv to prevent conflicts between host and container dependencies.
    ports:
      - "5000:5000"
    networks:
      - app-network
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    image: kanban-board-client
    container_name: kanban-board-client
    command: yarn start
    depends_on:
      - server
    volumes:
      - ./client/:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "3000:3000"
    networks:
      - app-network
    environment:
      # for hot reloading in development mode
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true

# Config network to allow containers within the same network to communicate directly while isolating them from external containers.
networks:
  app-network:
    driver: bridge

volumes:
  node_modules:
